# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d68da8911c0f5a817702e33938bedd808a5897f1d55f90bc094f2baeb1f985f9086c497d367ea1dcf167fe4e6decf180bcad966baeb009c9206419631f8b6f

test:
  secret_key_base: 6a933f505241a4b7710eb89130cc49d7e3738d2052f83685eb7cf1f023fd414e2d94be1594b6a58658cd0500cd41be877736be72e74fedc3a4f803ae3d3eaa19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
